# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        # Runs a single command using the runners shell
        - name: Run a one-line script
          run: echo Hello, world!

        # Runs a set of commands using the runners shell
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
    list_repos:
      name: README Repos List
      # You may pin to the exact commit or the version.
      # uses: AnandChowdhary/readme-repos-list@779449bb49f0da6c9221ee05066de8493ec0d9a2
      uses: AnandChowdhary/readme-repos-list@v1.1.1
      with:
        # GitHub token
        token: ${{ secrets.LIST_ACTION_GITHUB_TOKEN }}
        # Search query to find repositories
        query: tdc-vellore
        # Owner of repository to commit in
        owner: tdc-vellore # optional
        # Name of repository to commit in
        repo: glossary # optional
        # Maximum number of repositories to add
        # max: # optional
        # Prefix content to add before list
        # prefix: # optional
        # Query parameters for image manipulation
        # weserv-query: # optional
        # Link to repository, not homepage (if found)
        # no-homepage: # optional
        # Suffix content to add after list
        # suffix: # optional
        # File path, defaults to README.md
        # path: # optional
        # Starting comment to look for
        # start: # optional
        # Ending commit to look for
        # end: # optional
        # Commit message when updating file
        # commit-message: # optional
        # Show only one repository per owner
        # one-per-owner: # optional
        # Sort repositories by...
        sort: name # optional
        # Order by desc or asc
        order: asc # optional
